name: Secrets Demo
on: [push]

jobs:
  use-Secrets:
    runs-on: ubunto-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Print Secret
        env:
          MY_SECRET_VAL: ${{ secrets.MY_SECRET_VAL }}
        run: | 
          echo "Printing secret directly (masked): ${{ secrets.MY_SECRET_VAL }}"
          echo "Printing secret from env (masked): $MY_SECRET_VAL"